"use client";

import { Check, Copy, Radio, RefreshCw } from "lucide-react";
import { Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { Medication } from "@/types/database";

export function LinkTagPage() { return <Suspense fallback={null}><LinkTagForm /></Suspense>; }
function makeIdentifier() { return `med-${crypto.randomUUID()}`; }
function LinkTagForm() {
  const searchParams = useSearchParams(); const [items, setItems] = useState<Medication[]>([]); const [medicationId, setMedicationId] = useState(searchParams.get("medication") ?? ""); const [identifier, setIdentifier] = useState(""); const [origin, setOrigin] = useState(""); const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const url = useMemo(() => identifier && origin ? `${origin}/nfc?id=${encodeURIComponent(identifier)}` : "", [identifier, origin]);
  useEffect(() => { setOrigin(window.location.origin); createClient().from("medications").select("id,name,description,photo_url,color,active,dose,unit,nfc_identifier").order("name").then(({ data }) => { const medications = data ?? []; setItems(medications); const selected = medications.find((item) => item.id === medicationId); setIdentifier(selected?.nfc_identifier ?? (medicationId ? makeIdentifier() : "")); }); }, []);
  function choose(id: string) { setMedicationId(id); setIdentifier(items.find((item) => item.id === id)?.nfc_identifier ?? (id ? makeIdentifier() : "")); setSaved(false); setError(""); }
  async function save(event: React.FormEvent) { event.preventDefault(); setError(""); setSaved(false); if (!medicationId || !identifier) return setError("Selecciona un medicamento y genera su identificador."); const { error } = await createClient().from("medications").update({ nfc_identifier: identifier, nfc_uid: identifier }).eq("id", medicationId); if (error) return setError(error.code === "23505" ? "No se pudo generar un identificador único. Inténtalo de nuevo." : error.message); setItems(items.map((item) => item.id === medicationId ? { ...item, nfc_identifier: identifier } : item)); setSaved(true); }
  async function copy() { if (url) await navigator.clipboard.writeText(url); }
  return <><header><p className="text-sm font-semibold text-blue-600">ETIQUETAS NFC</p><h1 className="mt-1 text-3xl font-bold">Vincular etiqueta</h1><p className="mt-1 text-slate-500">Genera la URL que escribirás en la pegatina NFC.</p></header><section className="card mt-8 max-w-xl p-6"><div className="flex gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><Radio size={21} /></span><p className="text-sm leading-6 text-slate-500">La etiqueta no depende de su UID físico: contiene una URL única del medicamento. Puedes escribir esa URL con una app NFC de tu teléfono.</p></div><form onSubmit={save} className="mt-6 space-y-5"><label className="block text-sm font-semibold">Medicamento<select required className="field mt-1.5" value={medicationId} onChange={(event) => choose(event.target.value)}><option value="">Selecciona un medicamento</option>{items.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>{medicationId && <><div><p className="text-sm font-semibold">Identificador único</p><div className="mt-1.5 flex gap-2"><input readOnly className="field min-w-0 font-mono text-xs" value={identifier} /><button type="button" onClick={() => { setIdentifier(makeIdentifier()); setSaved(false); }} className="button button-secondary px-3" title="Generar otro identificador"><RefreshCw size={17} /></button></div></div><div><p className="text-sm font-semibold">URL para escribir en la etiqueta</p><div className="mt-1.5 flex gap-2"><input readOnly className="field min-w-0 font-mono text-xs" value={url} /><button type="button" onClick={copy} className="button button-secondary px-3" title="Copiar URL"><Copy size={17} /></button></div></div></>}{error && <p className="text-sm text-rose-600">{error}</p>}{saved && <p className="flex items-center gap-2 text-sm font-semibold text-emerald-600"><Check size={17} />Etiqueta vinculada correctamente. Ya puedes escribir la URL mostrada.</p>}<button className="button" disabled={!medicationId}>Guardar vinculación</button></form></section></>;
}
