"use client";

import { Edit3, Plus, Power, Radio, Trash2, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { Medication } from "@/types/database";

const colors = ["#2563eb", "#7c3aed", "#db2777", "#ea580c", "#16a34a", "#0891b2"];
type MedicationRecord = Medication & { schedules: { id: string; time: string; days_of_week: number[] }[]; photo_preview?: string };
export function MedicationsPage() {
  const [items, setItems] = useState<MedicationRecord[]>([]); const [editing, setEditing] = useState<MedicationRecord | null | undefined>();
  async function load() { const supabase = createClient(); const { data } = await supabase.from("medications").select("*,schedules(*)").order("name"); const records = await Promise.all((data ?? []).map(async (item) => { if (!item.photo_url) return item; const { data: image } = await supabase.storage.from("medication-photos").createSignedUrl(item.photo_url, 3600); return { ...item, photo_preview: image?.signedUrl }; })); setItems(records); }
  useEffect(() => { load(); }, []);
  async function toggle(item: MedicationRecord) { await createClient().from("medications").update({ active: !item.active }).eq("id", item.id); load(); }
  async function remove(item: MedicationRecord) { if (!confirm(`¿Eliminar ${item.name}? También se eliminarán sus horarios y tomas.`)) return; await createClient().from("medications").delete().eq("id", item.id); if (item.photo_url) await createClient().storage.from("medication-photos").remove([item.photo_url]); load(); }
  return <><header className="flex items-center justify-between"><div><p className="text-sm font-semibold text-blue-600">TU TRATAMIENTO</p><h1 className="mt-1 text-3xl font-bold">Medicamentos</h1></div><button onClick={() => setEditing(null)} className="button"><Plus size={18} />Añadir</button></header><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item.id} className="card overflow-hidden"><div className="flex min-h-28 items-start justify-between p-5" style={{ background: `${item.color}12` }}>{item.photo_preview ? <img src={item.photo_preview} alt="" className="size-16 rounded-2xl object-cover" /> : <span className="size-14 rounded-2xl" style={{ backgroundColor: item.color }} />}<span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{item.active ? "Activo" : "Pausado"}</span></div><div className="p-5"><h2 className="text-lg font-bold">{item.name}</h2><p className="mt-1 text-sm font-semibold text-slate-600">{item.dose ? `${item.dose} ${item.unit ?? ""}` : "Dosis sin indicar"}</p><p className="mt-2 min-h-10 text-sm text-slate-500">{item.description || "Sin descripción"}</p><p className="mt-3 text-xs text-slate-400">{item.schedules.length} horario(s) · {item.nfc_uid || "Sin etiqueta NFC"}</p><div className="mt-5 flex gap-2"><Link href={`/link-tag?medication=${item.id}`} className="button button-secondary px-3" title="Vincular etiqueta"><Radio size={16} /></Link><button onClick={() => setEditing(item)} className="button button-secondary flex-1"><Edit3 size={16} />Editar</button><button onClick={() => toggle(item)} title={item.active ? "Desactivar" : "Activar"} className="rounded-xl bg-slate-100 px-3 text-slate-600"><Power size={17} /></button><button onClick={() => remove(item)} title="Eliminar" className="rounded-xl bg-rose-50 px-3 text-rose-600"><Trash2 size={17} /></button></div></div></article>)}</div>{items.length === 0 && <div className="card mt-8 p-10 text-center text-slate-500">No has añadido ningún medicamento todavía.</div>}{editing !== undefined && <MedicationForm medication={editing} close={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); load(); }} />}</>;
}
function MedicationForm({ medication, close, onSaved }: { medication: MedicationRecord | null; close: () => void; onSaved: () => void }) {
  const [color, setColor] = useState(medication?.color ?? colors[0]); const [times, setTimes] = useState<string[]>(medication?.schedules.map((schedule) => schedule.time.slice(0, 5)) ?? [""]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function save(formData: FormData) { setSaving(true); setError(""); const supabase = createClient(); let photoUrl = medication?.photo_url ?? null; const file = formData.get("photo") as File; if (file?.size) { const { data: { user } } = await supabase.auth.getUser(); if (!user) { setSaving(false); return setError("Debes iniciar sesión."); } const path = `${user.id}/${crypto.randomUUID()}.${file.name.split(".").pop() || "jpg"}`; const { error: uploadError } = await supabase.storage.from("medication-photos").upload(path, file); if (uploadError) { setSaving(false); return setError(uploadError.message); } photoUrl = path; } const payload = { name: String(formData.get("name")).trim(), description: String(formData.get("description")).trim() || null, dose: Number(formData.get("dose")) || null, unit: String(formData.get("unit")).trim() || null, color, photo_url: photoUrl }; const response = medication ? await supabase.from("medications").update(payload).eq("id", medication.id).select("id").single() : await supabase.from("medications").insert(payload).select("id").single(); if (response.error || !response.data) { setSaving(false); return setError(response.error?.message ?? "No se pudo guardar."); } const medicationId = response.data.id; await supabase.from("schedules").delete().eq("medication_id", medicationId); const validTimes = times.filter(Boolean); if (validTimes.length) await supabase.from("schedules").insert(validTimes.map((time) => ({ medication_id: medicationId, time, days_of_week: [0, 1, 2, 3, 4, 5, 6] }))); setSaving(false); onSaved(); }
  return <div className="fixed inset-0 z-20 grid place-items-end bg-slate-950/30 p-0 sm:place-items-center sm:p-5"><form action={save} className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{medication ? "Editar medicamento" : "Nuevo medicamento"}</h2><button type="button" onClick={close} className="rounded-lg p-2 text-slate-500"><X /></button></div><label className="mt-6 block text-sm font-semibold">Nombre<input name="name" required defaultValue={medication?.name} className="field mt-1.5" /></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="block text-sm font-semibold">Dosis<input name="dose" type="number" min="0" step="any" defaultValue={medication?.dose ?? ""} className="field mt-1.5" placeholder="500" /></label><label className="block text-sm font-semibold">Unidad<input name="unit" defaultValue={medication?.unit ?? ""} className="field mt-1.5" placeholder="mg, ml, cápsulas…" /></label></div><label className="mt-4 block text-sm font-semibold">Descripción <span className="font-normal text-slate-400">(opcional)</span><textarea name="description" defaultValue={medication?.description ?? ""} className="field mt-1.5 min-h-20 resize-none" /></label><label className="mt-4 block text-sm font-semibold">Foto <span className="font-normal text-slate-400">(opcional)</span><input name="photo" type="file" accept="image/*" className="mt-1.5 block w-full text-sm" /></label><div className="mt-4"><p className="text-sm font-semibold">Horarios diarios</p>{times.map((time, index) => <div className="mt-2 flex gap-2" key={index}><input type="time" value={time} onChange={(event) => setTimes(times.map((current, i) => i === index ? event.target.value : current))} className="field" />{times.length > 1 && <button type="button" onClick={() => setTimes(times.filter((_, i) => i !== index))} className="rounded-xl bg-rose-50 px-3 text-rose-600"><X size={17} /></button>}</div>)}<button type="button" onClick={() => setTimes([...times, ""])} className="mt-2 text-sm font-bold text-blue-600">+ Añadir horario</button></div><div className="mt-4"><p className="text-sm font-semibold">Color</p><div className="mt-2 flex gap-2">{colors.map((value) => <button type="button" key={value} onClick={() => setColor(value)} className={`size-8 rounded-full ring-offset-2 ${color === value ? "ring-2 ring-slate-700" : ""}`} style={{ backgroundColor: value }} />)}</div></div>{error && <p className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-6 flex gap-3"><button type="button" onClick={close} className="button button-secondary flex-1">Cancelar</button><button disabled={saving} className="button flex-1">{saving ? "Guardando…" : "Guardar"}</button></div></form></div>;
}
