"use client";

import Link from "next/link";
import { CheckCircle2, CircleAlert, Radio } from "lucide-react";
import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Result = { kind: "success" | "duplicate" | "error" | "login"; title: string; detail: string };
export default function NfcPage() { return <Suspense fallback={<NfcLoading />}><NfcProcessor /></Suspense>; }
function NfcLoading() { return <main className="grid min-h-screen place-items-center p-5"><section className="card w-full max-w-md p-8 text-center"><p className="text-sm text-slate-500">Procesando etiqueta…</p></section></main>; }
function NfcProcessor() {
  const searchParams = useSearchParams(); const identifier = searchParams.get("id"); const [result, setResult] = useState<Result | null>(null);
  useEffect(() => { async function processTag() { if (!identifier) return setResult({ kind: "error", title: "Falta el identificador", detail: "Añade el parámetro id a la URL de la etiqueta NFC." }); const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return setResult({ kind: "login", title: "Inicia sesión", detail: "Debes iniciar sesión para registrar una toma mediante NFC." }); const [{ data: profile }, { data: medication, error: medicationError }] = await Promise.all([supabase.from("profiles").select("nfc_duplicate_window_hours").eq("id", user.id).single(), supabase.from("medications").select("id,name,active").eq("nfc_identifier", identifier).single()]); if (medicationError || !medication) return setResult({ kind: "error", title: "Etiqueta no encontrada", detail: "El identificador de esta URL no está asociado a ningún medicamento de tu cuenta." }); if (!medication.active) return setResult({ kind: "error", title: "Medicamento pausado", detail: `${medication.name} está desactivado y no se ha registrado ninguna toma.` }); const hours = Number(profile?.nfc_duplicate_window_hours ?? 4); const since = new Date(Date.now() - hours * 60 * 60 * 1000).toISOString(); const { data: recent } = await supabase.from("intakes").select("taken_at").eq("medication_id", medication.id).gte("taken_at", since).order("taken_at", { ascending: false }).limit(1).maybeSingle(); if (recent) return setResult({ kind: "duplicate", title: "Toma ya registrada", detail: `Ya registrada la toma a las ${new Date(recent.taken_at).toLocaleTimeString("es-ES", { hour: "2-digit", minute: "2-digit" })}.` }); const { error: intakeError } = await supabase.from("intakes").insert({ medication_id: medication.id, method: "nfc" }); if (intakeError) return setResult({ kind: "error", title: "No se pudo registrar", detail: intakeError.message }); setResult({ kind: "success", title: "Toma registrada correctamente.", detail: `${medication.name} ha quedado registrado mediante NFC.` }); } processTag(); }, [identifier]);
  const icon = result?.kind === "success" ? <CheckCircle2 size={29} /> : result?.kind === "error" ? <CircleAlert size={29} /> : <Radio size={29} />; const tone = result?.kind === "success" ? "bg-emerald-50 text-emerald-600" : result?.kind === "error" ? "bg-rose-50 text-rose-600" : "bg-blue-50 text-blue-600";
  return <main className="grid min-h-screen place-items-center p-5"><section className="card w-full max-w-md p-8 text-center"><span className={`mx-auto grid size-14 place-items-center rounded-2xl ${tone}`}>{icon}</span>{!result ? <><h1 className="mt-5 text-2xl font-bold">Procesando etiqueta…</h1><p className="mt-3 text-sm text-slate-500">Comprobando la última toma registrada.</p></> : <><h1 className="mt-5 text-2xl font-bold">{result.title}</h1><p className="mt-3 text-sm leading-6 text-slate-500">{result.detail}</p>{identifier && <code className="mt-5 block rounded-lg bg-slate-100 p-3 text-xs text-slate-500">ID: {identifier}</code>}<Link href={result.kind === "login" ? "/login" : "/"} className="button mt-6">{result.kind === "login" ? "Iniciar sesión" : "Ir al panel"}</Link></>}</section></main>;
}
